const toEnum = (values) => Object.freeze(Object.fromEntries(values.map((v) => [v, v])));

const ROLES = toEnum(['OWNER', 'ACCOUNTANT', 'WORKER', 'CUSTOMER']);
const STAFF_ROLES = [ROLES.OWNER, ROLES.ACCOUNTANT, ROLES.WORKER];

const WORKER_ROLES = toEnum([
  'CARPENTER',
  'ASSEMBLER',
  'UPHOLSTERER',
  'PAINTER',
  'DESIGNER',
  'INSTALLER',
  'FINISHER',
  'SUPERVISOR',
]);

const PRODUCTION_STAGES = toEnum([
  'PENDING',
  'APPROVED',
  'MATERIALS_REQUIRED',
  'MATERIALS_READY',
  'IN_PRODUCTION',
  'ASSEMBLY',
  'FINISHING',
  'QUALITY_CHECK',
  'READY_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED',
]);

const ORDER_STATUS = toEnum([
  'PENDING',
  'CONFIRMED',
  'PAID',
  'IN_PRODUCTION',
  'READY',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'COMPLETED',
  'CANCELLED',
]);

const PAYMENT_STATUS = toEnum(['UNPAID', 'PARTIAL', 'PAID', 'REFUNDED']);
const DELIVERY_STATUS = toEnum(['PENDING', 'SCHEDULED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED']);
const DELIVERY_METHODS = toEnum(['DELIVERY', 'PICKUP']);
const QC_STATUS = toEnum(['PENDING', 'PASSED', 'FAILED', 'REWORK_REQUIRED']);
const QC_CHECK_ITEMS = [
  'dimensions',
  'structure',
  'finishing',
  'color',
  'materialQuality',
  'assembly',
  'customerSpecifications',
  'defects',
  'cleanliness',
  'packaging',
];

const TRANSACTION_TYPES = toEnum([
  'SALE',
  'CUSTOMER_PAYMENT',
  'EXPENSE',
  'SUPPLIER_PAYMENT',
  'WORKER_PAYMENT',
  'REFUND',
  'PURCHASE',
  'OTHER_INCOME',
  'DISCOUNT',
]);

// Cash direction of each transaction type. NONE = recorded for the books but no cash moved.
const TRANSACTION_DIRECTION = Object.freeze({
  SALE: 'NONE',
  CUSTOMER_PAYMENT: 'IN',
  OTHER_INCOME: 'IN',
  EXPENSE: 'OUT',
  SUPPLIER_PAYMENT: 'OUT',
  WORKER_PAYMENT: 'OUT',
  REFUND: 'OUT',
  PURCHASE: 'NONE',
  DISCOUNT: 'NONE',
});

const PAYMENT_METHODS = toEnum(['CASH', 'BANK_TRANSFER', 'MOBILE_PAYMENT', 'CARD', 'OTHER']);
const PAYMENT_CATEGORIES = toEnum(['CUSTOMER_PAYMENT', 'SUPPLIER_PAYMENT', 'WORKER_PAYMENT', 'REFUND']);

const INVENTORY_TX_TYPES = toEnum([
  'STOCK_IN',
  'STOCK_OUT',
  'ADJUSTMENT',
  'DAMAGED',
  'SALE',
  'RETURN',
  'PURCHASE_RECEIPT',
  'PRODUCTION_ISSUE',
  'PRODUCTION_RETURN',
  'TRANSFER',
  'PRODUCTION_OUTPUT',
]);

const CUSTOM_REQUEST_STATUS = toEnum([
  'SUBMITTED',
  'UNDER_REVIEW',
  'ESTIMATED',
  'QUOTED',
  'APPROVED',
  'REJECTED',
  'CANCELLED',
  'CONVERTED',
]);

const PRODUCT_STATUS = toEnum(['ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED']);

const EXPENSE_CATEGORIES = toEnum([
  'RENT',
  'UTILITIES',
  'SALARIES',
  'TRANSPORT',
  'MAINTENANCE',
  'MARKETING',
  'MATERIALS',
  'EQUIPMENT',
  'TAXES',
  'OTHER',
]);
const EXPENSE_STATUS = toEnum(['PENDING', 'APPROVED', 'REJECTED']);

const PURCHASE_STATUS = toEnum(['DRAFT', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED']);
const INVOICE_STATUS = toEnum(['ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID']);
const TASK_STATUS = toEnum(['TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE']);
const PRIORITIES = toEnum(['LOW', 'NORMAL', 'HIGH', 'URGENT']);

const AUDIT_ACTIONS = toEnum([
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'CREATE',
  'UPDATE',
  'DELETE',
  'PAYMENT',
  'REFUND',
  'STATUS_CHANGE',
  'INVENTORY_CHANGE',
  'PRODUCTION_CHANGE',
  'PERMISSION_CHANGE',
  'APPROVAL',
]);

const NOTIFICATION_TYPES = toEnum([
  'NEW_ORDER',
  'NEW_CUSTOMER',
  'LOW_STOCK',
  'PRODUCTION_DELAY',
  'LARGE_EXPENSE',
  'PAYMENT_RECEIVED',
  'NEW_EXPENSE',
  'CUSTOMER_DEBT',
  'SUPPLIER_PAYMENT',
  'JOB_ASSIGNED',
  'TASK_DEADLINE',
  'MATERIAL_AVAILABLE',
  'MATERIAL_REQUEST',
  'PRODUCTION_UPDATE',
  'PRODUCTION_PROBLEM',
  'ORDER_CONFIRMED',
  'PRODUCTION_STARTED',
  'PRODUCTION_COMPLETED',
  'READY_FOR_DELIVERY',
  'DELIVERED',
  'PAYMENT_REMINDER',
  'CUSTOM_REQUEST',
  'QUOTE_READY',
  'MESSAGE',
  'APPROVAL_REQUIRED',
  'GENERAL',
]);

module.exports = {
  ROLES,
  STAFF_ROLES,
  WORKER_ROLES,
  PRODUCTION_STAGES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  DELIVERY_STATUS,
  DELIVERY_METHODS,
  QC_STATUS,
  QC_CHECK_ITEMS,
  TRANSACTION_TYPES,
  TRANSACTION_DIRECTION,
  PAYMENT_METHODS,
  PAYMENT_CATEGORIES,
  INVENTORY_TX_TYPES,
  CUSTOM_REQUEST_STATUS,
  PRODUCT_STATUS,
  EXPENSE_CATEGORIES,
  EXPENSE_STATUS,
  PURCHASE_STATUS,
  INVOICE_STATUS,
  TASK_STATUS,
  PRIORITIES,
  AUDIT_ACTIONS,
  NOTIFICATION_TYPES,
};
