import { Link } from 'react-router-dom';
import { StatusBadge } from '../../../components/ui/Badge';
import { date, label, money, number } from '../../../utils/format';

const m = (key, header, extra = {}) => ({ key, header, align: 'right', render: (r) => money(r[key]), exportValue: (r) => r[key], ...extra });
const n = (key, header, extra = {}) => ({ key, header, align: 'right', render: (r) => number(r[key]), ...extra });

/**
 * Each report: which filters it supports, how to pick rows out of the API response,
 * the table columns, summary figures and an optional chart.
 */
export const REPORTS = [
  {
    key: 'sales',
    title: 'Sales report',
    group: 'Sales',
    perm: 'reports:financial',
    filters: ['period', 'dates', 'customer', 'product', 'branch'],
    rows: (d) => d.rows,
    columns: [
      { key: 'period', header: 'Period' },
      n('orders', 'Orders'),
      m('grossSales', 'Gross sales'),
      m('discounts', 'Discounts'),
      m('tax', 'VAT'),
      m('revenue', 'Revenue'),
      m('collected', 'Collected'),
      m('outstanding', 'Outstanding'),
    ],
    productColumns: [{ key: 'period', header: 'Period' }, n('orders', 'Orders'), n('quantity', 'Units'), m('revenue', 'Revenue')],
    summary: (d) => [
      ['Orders', number(d.totals.orders)],
      ['Revenue', money(d.totals.revenue)],
      ['Collected', money(d.totals.collected)],
      ['Outstanding', money(d.totals.outstanding)],
    ],
    chart: { type: 'bar', x: 'period', series: [{ key: 'revenue', name: 'Revenue' }, { key: 'collected', name: 'Collected', color: '#5f7f63' }] },
  },
  {
    key: 'product-sales',
    title: 'Product sales report',
    group: 'Sales',
    perm: 'reports:financial',
    filters: ['dates', 'customer', 'product', 'branch'],
    rows: (d) => d.rows,
    columns: [
      { key: 'name', header: 'Product' },
      { key: 'sku', header: 'SKU' },
      n('orders', 'Orders'),
      n('quantity', 'Units'),
      m('revenue', 'Revenue'),
      m('cost', 'Cost'),
      m('profit', 'Profit'),
      { key: 'margin', header: 'Margin', align: 'right', render: (r) => `${r.margin}%` },
    ],
    summary: (d) => [
      ['Units sold', number(d.totals.quantity)],
      ['Revenue', money(d.totals.revenue)],
      ['Profit', money(d.totals.profit)],
    ],
    chart: { type: 'hbar', x: 'name', series: [{ key: 'revenue', name: 'Revenue' }], limit: 10 },
  },
  {
    key: 'profit-loss',
    title: 'Profit & loss',
    group: 'Finance',
    perm: 'reports:financial',
    filters: ['period', 'dates'],
    rows: (d) => d.rows,
    columns: [
      { key: 'period', header: 'Period' },
      m('sales', 'Sales booked'),
      m('income', 'Income received'),
      m('refunds', 'Refunds'),
      m('expenses', 'Expenses'),
      m('supplierPayments', 'Supplier payments'),
      m('workerPayments', 'Wages'),
      m('profit', 'Net profit', { render: (r) => <span className={r.profit < 0 ? 'font-semibold text-red-600' : 'font-semibold text-emerald-700'}>{money(r.profit)}</span> }),
    ],
    summary: (d) => [
      ['Net income', money(d.totals.netIncome)],
      ['Total costs', money(d.totals.totalCosts)],
      ['Net profit (cash)', money(d.totals.profit)],
      ['Gross profit on sales', money(d.totals.grossProfit)],
    ],
    chart: { type: 'area', x: 'period', series: [{ key: 'netIncome', name: 'Net income' }, { key: 'totalCosts', name: 'Costs', color: '#b45353' }, { key: 'profit', name: 'Profit', color: '#5f7f63' }] },
  },
  {
    key: 'expenses',
    title: 'Expense report',
    group: 'Finance',
    perm: 'reports:financial',
    filters: ['dates', 'expenseCategory', 'method', 'branch'],
    rows: (d) => d.rows,
    columns: [
      { key: 'expenseNumber', header: 'Number' },
      { key: 'date', header: 'Date', render: (r) => date(r.date), exportValue: (r) => date(r.date) },
      { key: 'category', header: 'Category', render: (r) => label(r.category) },
      { key: 'description', header: 'Description' },
      { key: 'vendor', header: 'Vendor' },
      { key: 'method', header: 'Method', render: (r) => label(r.method) },
      m('amount', 'Amount'),
    ],
    summary: (d) => [['Total expenses', money(d.totals.amount)], ...d.byCategory.slice(0, 4).map((c) => [label(c.category), money(c.amount)])],
    chart: { type: 'donut', data: (d) => d.byCategory, name: 'category', value: 'amount' },
  },
  {
    key: 'payments',
    title: 'Payment report',
    group: 'Finance',
    perm: 'reports:financial',
    filters: ['dates', 'customer', 'method', 'paymentCategory'],
    rows: (d) => d.rows,
    columns: [
      { key: 'receiptNumber', header: 'Receipt', render: (r) => r.receiptNumber || r.paymentNumber },
      { key: 'date', header: 'Date', render: (r) => date(r.date), exportValue: (r) => date(r.date) },
      { key: 'category', header: 'Type', render: (r) => label(r.category) },
      { key: 'party', header: 'Party' },
      { key: 'order', header: 'Order' },
      { key: 'method', header: 'Method', render: (r) => label(r.method) },
      { key: 'reference', header: 'Reference' },
      m('amount', 'Amount'),
    ],
    summary: (d) => [['Total', money(d.totals.amount)], ...d.byMethod.slice(0, 4).map((x) => [`${label(x.method)} (${label(x.category)})`, money(x.amount)])],
    chart: { type: 'donut', data: (d) => d.byMethod.filter((x) => x.category === 'CUSTOMER_PAYMENT'), name: 'method', value: 'amount' },
  },
  {
    key: 'transactions',
    title: 'Transactions',
    group: 'Finance',
    perm: 'reports:financial',
    filters: ['dates', 'customer', 'method', 'transactionType'],
    rows: (d) => d.rows,
    columns: [
      { key: 'transactionNumber', header: 'Number' },
      { key: 'date', header: 'Date', render: (r) => date(r.date), exportValue: (r) => date(r.date) },
      { key: 'type', header: 'Type', render: (r) => label(r.type) },
      { key: 'description', header: 'Description' },
      { key: 'customer', header: 'Customer' },
      { key: 'method', header: 'Method', render: (r) => label(r.method) },
      m('amount', 'Amount', { render: (r) => <span className={r.direction === 'OUT' ? 'text-red-600' : r.direction === 'IN' ? 'text-emerald-700' : ''}>{money(r.amount)}</span> }),
    ],
    summary: (d) => [
      ['Money in', money(d.totals.moneyIn)],
      ['Money out', money(d.totals.moneyOut)],
      ['Net', money(d.totals.net)],
    ],
  },
  {
    key: 'customer-debts',
    title: 'Customer debt report',
    group: 'Debts',
    perm: 'reports:financial',
    filters: ['customer'],
    rows: (d) => d.rows,
    columns: [
      { key: 'customer', header: 'Customer', render: (r) => <Link className="link" to={`/app/customers/${r.customerId}`}>{r.customer}</Link>, exportValue: (r) => r.customer },
      { key: 'phone', header: 'Phone' },
      { key: 'orderNumbers', header: 'Orders', render: (r) => r.orderNumbers.join(', '), exportValue: (r) => r.orderNumbers.join(' ') },
      m('totalBilled', 'Billed'),
      m('paid', 'Paid'),
      m('balance', 'Balance', { render: (r) => <span className="font-semibold text-brass-800">{money(r.balance)}</span> }),
      { key: 'daysOutstanding', header: 'Days', align: 'right', render: (r) => <span className={r.daysOutstanding > 30 ? 'font-semibold text-red-600' : ''}>{r.daysOutstanding}</span> },
    ],
    summary: (d) => [
      ['Customers owing', d.rows.length],
      ['Total outstanding', money(d.totals.balance)],
    ],
  },
  {
    key: 'supplier-debts',
    title: 'Supplier debt report',
    group: 'Debts',
    perm: 'reports:financial',
    filters: [],
    rows: (d) => d.rows,
    columns: [
      { key: 'supplier', header: 'Supplier', render: (r) => <Link className="link" to={`/app/suppliers/${r.supplierId}`}>{r.supplier}</Link>, exportValue: (r) => r.supplier },
      { key: 'phone', header: 'Phone' },
      { key: 'paymentTerms', header: 'Terms' },
      m('balance', 'We owe'),
    ],
    summary: (d) => [['Total owed to suppliers', money(d.totals.balance)]],
  },
  {
    key: 'customers',
    title: 'Customer report',
    group: 'Customers',
    perm: 'reports:financial',
    filters: ['dates', 'customer'],
    sections: (d) => [
      {
        title: 'Top customers',
        rows: d.topCustomers,
        columns: [{ key: 'customer', header: 'Customer' }, { key: 'phone', header: 'Phone' }, n('orders', 'Orders'), m('spent', 'Spent'), m('balance', 'Balance'), { key: 'lastOrder', header: 'Last order', render: (r) => date(r.lastOrder), exportValue: (r) => date(r.lastOrder) }],
      },
      { title: 'Repeat customers', rows: d.repeatCustomers, columns: [{ key: 'customer', header: 'Customer' }, n('orders', 'Orders'), m('spent', 'Spent')] },
      { title: 'New customers in period', rows: d.newCustomers, columns: [{ key: 'name', header: 'Customer' }, { key: 'customerCode', header: 'Code' }, { key: 'phone', header: 'Phone' }, { key: 'source', header: 'Source', render: (r) => label(r.source) }, { key: 'createdAt', header: 'Joined', render: (r) => date(r.createdAt), exportValue: (r) => date(r.createdAt) }] },
      { title: 'Outstanding balances', rows: d.outstanding, columns: [{ key: 'customer', header: 'Customer' }, n('orders', 'Orders'), m('balance', 'Balance')] },
      ...(d.history.length ? [{ title: 'Order history', rows: d.history, columns: [{ key: 'orderNumber', header: 'Order' }, { key: 'orderDate', header: 'Date', render: (r) => date(r.orderDate) }, { key: 'status', header: 'Status', render: (r) => <StatusBadge status={r.status} />, exportValue: (r) => r.status }, m('total', 'Total'), m('balance', 'Balance')] }] : []),
    ],
    summary: (d) => [
      ['Total customers', d.totals.totalCustomers],
      ['New in period', d.totals.newCustomers],
      ['Repeat customers', d.totals.repeatCustomers],
    ],
  },
  {
    key: 'production',
    title: 'Production report',
    group: 'Operations',
    perm: 'reports:operations',
    filters: ['dates'],
    sections: (d) => [
      {
        title: 'Completed jobs',
        rows: d.completed,
        columns: [{ key: 'jobNumber', header: 'Job' }, { key: 'title', header: 'Furniture' }, n('productionDays', 'Days'), n('reworkCount', 'Reworks'), { key: 'onTime', header: 'On time', render: (r) => (r.onTime ? 'Yes' : 'Late') }, { key: 'actualCompletionDate', header: 'Completed', render: (r) => date(r.actualCompletionDate), exportValue: (r) => date(r.actualCompletionDate) }],
      },
      { title: 'Delayed jobs', rows: d.delayed, columns: [{ key: 'jobNumber', header: 'Job' }, { key: 'title', header: 'Furniture' }, { key: 'stage', header: 'Stage', render: (r) => label(r.stage) }, n('daysLate', 'Days late'), { key: 'workers', header: 'Workers', render: (r) => r.assignedWorkers?.map((w) => w.name).join(', '), exportValue: (r) => r.assignedWorkers?.map((w) => w.name).join('; ') }] },
      { title: 'Worker workload', rows: d.workload, columns: [{ key: 'worker', header: 'Worker' }, { key: 'position', header: 'Position', render: (r) => label(r.position) }, n('activeJobs', 'Active'), n('completedInRange', 'Completed'), n('overdue', 'Overdue'), n('reworks', 'Reworks')] },
      { title: 'Jobs by stage', rows: d.byStage, columns: [{ key: 'stage', header: 'Stage', render: (r) => label(r.stage) }, n('count', 'Jobs')] },
    ],
    summary: (d) => [
      ['Completed', d.totals.completed],
      ['Delayed', d.totals.delayed],
      ['Avg. production days', d.totals.averageProductionDays],
      ['On-time rate', `${d.totals.onTimeRate}%`],
    ],
  },
  {
    key: 'inventory',
    title: 'Inventory report',
    group: 'Operations',
    perm: 'reports:operations',
    filters: ['dates'],
    sections: (d) => [
      { title: 'Low stock', rows: d.lowStock, columns: [{ key: 'type', header: 'Type' }, { key: 'name', header: 'Item' }, n('quantity', 'Quantity'), n('minStock', 'Minimum'), { key: 'unit', header: 'Unit' }] },
      { title: 'Material usage in period', rows: d.usage, columns: [{ key: 'material', header: 'Material' }, n('used', 'Used'), { key: 'unit', header: 'Unit' }, m('cost', 'Cost')] },
      { title: 'Inventory movement', rows: d.movement, columns: [{ key: 'itemType', header: 'Item type', render: (r) => label(r.itemType) }, { key: 'type', header: 'Movement', render: (r) => label(r.type) }, n('quantity', 'Net quantity'), n('entries', 'Entries')] },
      { title: 'Materials — current stock', rows: d.materials, columns: [{ key: 'name', header: 'Material' }, { key: 'code', header: 'Code' }, n('quantity', 'Qty'), { key: 'unit', header: 'Unit' }, m('unitCost', 'Unit cost'), m('stockValue', 'Value')] },
      { title: 'Products — current stock', rows: d.products, columns: [{ key: 'name', header: 'Product' }, { key: 'sku', header: 'SKU' }, n('quantity', 'Qty'), n('soldQuantity', 'Sold'), n('damagedQuantity', 'Damaged'), m('stockValue', 'Value')] },
    ],
    summary: (d) => [
      ['Finished goods value', money(d.totals.productStockValue)],
      ['Materials value', money(d.totals.materialStockValue)],
      ['Low-stock items', d.totals.lowStockCount],
    ],
  },
];
